trigger:
- main
 
pool: Default
 
steps:
- script: |
    python3 --version
  displayName: 'Show Python version'
 
- script: |
    python3 -m pip install --upgrade pip
    python3 -m pip install -r requirements.txt
  displayName: 'Install dependencies'
 
- script: |
    /home/ubuntu/.local/bin/pytest
  displayName: 'Run tests'
 